version: 3

services:
  exosuite-users-api-postgres-standbox:
    restart: on-failure
    image: mdillon/postgis:11-alpine
    ports:
      - 5432:5432
    container_name: exosuite-users-api-postgres-standbox
    environment:
      - POSTGRES_DB=exosuite-users-api
      - POSTGRES_USER=exosuite
      - POSTGRES_PASSWORD=goTgxCtf5WCApNB8uce3YxJcjyevy3
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /var/www/exosuite-users-api-postgres-standbox:/var/lib/postgresql/data/pgdata